module.exports = {
  async up(queryInterface, Sequelize) {
    const tripArr = [
      {
        tripName: 'Поездка на Байкал',
        date: '2023-02-20',
        cityStart: 'Cанкт-Петербург',
        cityWhere: 'Иркутск',
        aboutMembers: 'Ищу активных путешественников, которые не боятся холода и готовы увидеть вживую всю красоту зимнего Байкала!',
        aboutTrip: 'Планирую пробыть на Байкале около недели. Покататься на коньках по озеру, проехаться на знаменитом хивусе и посетить Ольхон.',
        membersCount: 5,
        tripPhoto: 'images/baikal.jpeg',
        userId: 3,
      },
      {
        tripName: 'Осенний Дагестан',
        date: '2022-10-15',
        cityStart: 'Москва',
        cityWhere: 'Махачкала',
        aboutMembers: 'Если ты любишь горы также, как и я, не боишься сложностей и готов подниматься пешком, чтобы увидеть красоту Гамсутля высоко в горах, то ты тот, кто мне нужен!',
        aboutTrip: 'Планирую арендовать машину в Махачкале и самостоятель построить маршрут по красотам Дагестана. Планирую пробыть там около 5 дней',
        membersCount: 3,
        tripPhoto: 'images/dagestan.jpeg',
        userId: 2,
      },
      {
        tripName: 'Райский остров',
        date: '2023-02-10',
        cityStart: 'Краснодар',
        cityWhere: 'Мальдивы',
        aboutMembers: 'Семейные пары присоединяйтесь)',
        aboutTrip: 'Релакс отдых с восхитительными видами и кристально прозрачной водой на фоне белоснежных песчаных пляжей. Нереальные фото обеспеченны',
        membersCount: 10,
        tripPhoto: 'images/maldiv.jpeg',
        userId: 8,
      },
      {
        tripName: 'Йога тур',
        date: '2022-11-27',
        cityStart: 'Иркутск',
        cityWhere: 'Пхукет',
        aboutMembers: 'Кто готов погрузиться в новую философию, достичь духовного равновесия и улучшить состояние своего здоровья',
        aboutTrip: 'Красивое и здоровое тело, молодость, сила духа, энергия, женственность,  любовь и изобилие',
        membersCount: 15,
        tripPhoto: 'images/tay.jpeg',
        userId: 4,
      },
      {
        tripName: 'Париж... ах Париж',
        date: '2022-11-10',
        cityStart: 'Москва',
        cityWhere: 'Париж',
        aboutMembers: 'Любителей истории, искусства. Готовые часами блуждать по живописным улочкам.',
        aboutTrip: 'Триумфальная арка, Лувр, Эйфелева башня... и конечно же хруст свежеиспеченного круассана с чашечкой ароматногоо кофе... ',
        membersCount: 5,
        tripPhoto: 'images/paris.jpeg',
        userId: 7,
      },
      {
        tripName: 'Страна Восходящего Солнца',
        date: '2022-02-10',
        cityStart: 'Москва',
        cityWhere: 'Токио',
        aboutMembers: 'Молодые, активные и веселые',
        aboutTrip: 'Будем ездить на поездах и кушать суши))) Посетим горячии источники, сгоняем в Киото. Только движ)',
        membersCount: 6,
        tripPhoto: 'images/tokio.jpeg',
        userId: 5,
      },
      {
        tripName: 'Афины',
        date: '2023-06-23',
        cityStart: 'Cанкт-Петербург',
        cityWhere: 'Афины',
        aboutMembers: 'Если ты жаворонок и готов провести весь день на ногах - welcome',
        aboutTrip: 'Окунемся в античный мир, самого древнего города на земле.',
        membersCount: 8,
        tripPhoto: 'images/afin.jpeg',
        userId: 10,
      },
      {
        tripName: 'Вечный город Рим',
        date: '2023-05-15',
        cityStart: 'Мурманск',
        cityWhere: 'Рим',
        aboutMembers: 'Любителей пеших прогулок по историческим местам.',
        aboutTrip: 'Вас ждет отличное приключение. Вечный город, где смешались люди, эпохи, события — настоящая многовековая летопись в камне. Будем гулять и наслаждаться достопримечательностями этого Вечного города. ',
        membersCount: 5,
        tripPhoto: 'images/rim.webp',
        userId: 9,
      },
      {
        tripName: 'Сан-Франциско - город в стиле ДИСКО',
        date: '2023-05-11',
        cityStart: 'Москва',
        cityWhere: 'Сан-Франциско',
        aboutMembers: 'Любишь движ - GO с нами',
        aboutTrip: 'Заценим - Золотые ворота, квартал хиппи - чтобы ощутить СанФран. Посетим огромное количество мест для развлечений- это и парки , и пляжи, и клубы, и рестораны',
        membersCount: 5,
        tripPhoto: 'images/usa.jpeg',
        userId: 6,
      },
      {
        tripName: 'Казань на Авто',
        date: '2022-11-17',
        cityStart: 'Химки',
        cityWhere: 'Казань',
        aboutMembers: 'Если ты общительный и у тебя есть права категории В, присоединяйся к моей поездке',
        aboutTrip: 'Хочу проехать на авто, с заездом по дороге в красивые места и насладиться Татарской едой',
        membersCount: 4,
        tripPhoto: 'images/kazan.jpeg',
        userId: 4,
      },
      {
        tripName: 'Красноярские столбы',
        date: '2022-10-24',
        cityStart: 'Москва',
        cityWhere: 'Красноярск',
        aboutMembers: 'Для любителей природы и активного вида отдыха',
        aboutTrip: 'Лес, горы и чистый воздух!',
        membersCount: 10,
        tripPhoto: 'images/krasno.jpeg',
        userId: 5,
      },
      {
        tripName: 'Алтай',
        date: '2022-10-31',
        cityStart: 'Казань',
        cityWhere: 'Барнаул',
        aboutMembers: 'Для любителей ГОР и озёр!',
        aboutTrip: 'Посетим красивейшие места Алтая: горы, водопады, пещеры, озеры...',
        membersCount: 12,
        tripPhoto: 'images/altay.jpeg',
        userId: 8,
      },
      {
        tripName: 'Море, солнце и UAI ))',
        date: '2023-07-10',
        cityStart: 'Москва',
        cityWhere: 'Анталия',
        aboutMembers: 'Общительные, веселые, готовые на любой движ',
        aboutTrip: 'Хочу найти попутчиков на мега отрыв - лето2023, без нудных экскурсий и обычного валяния котиком на пляже',
        membersCount: 15,
        tripPhoto: 'images/tyrkish.jpeg',
        userId: 5,
      },
      {
        tripName: 'Австралия - Сидней - Серф',
        date: '2023-04-19',
        cityStart: 'Пермь',
        cityWhere: 'Сидней',
        aboutMembers: 'Не боишься промокнуть? Тогда лови волну со мной!',
        aboutTrip: 'Приличные волны ждут, чтобы их покорили',
        membersCount: 10,
        tripPhoto: 'images/sidney.jpeg',
        userId: 4,
      },
      {
        tripName: 'Кипр',
        date: '2022-10-27',
        cityStart: 'Москва',
        cityWhere: 'Ларнака',
        aboutMembers: 'Общительные с евроПравами категории В',
        aboutTrip: 'Посетить небольшой островок с райским климатом в Средиземноморье - легко можно на машине',
        membersCount: 6,
        tripPhoto: 'images/cyprus.jpeg',
        userId: 6,
      },
      {
        tripName: 'Регата в Греции',
        date: '2023-07-14',
        cityStart: 'Омск',
        cityWhere: 'Афины',
        aboutMembers: 'Любителям море и Яхт.',
        aboutTrip: 'Отличные гонки по островам Греции: Кос, Тилос, Нисирос, Сими, Родос. Соревнования для любителей.',
        membersCount: 8,
        tripPhoto: 'images/regata.jpeg',
        userId: 9,
      },
    ];

    await queryInterface.bulkInsert('Trips', tripArr, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Trips', null, {});
  },
};
