module.exports = {
  async up(queryInterface, Sequelize) {
    const usersArr = [
      {
        name: 'Ира&Спейс',
        email: 'ira@mail.ru',
        password: '123',
        phone: '8(916)764-62-81',
        social: 'https://www.instagram.com/veryire/',
        photo: 'images/ira.png',
        about: 'Всем привет! Меня зовут Ира. В прошлом я была редактором Cosmopolitan, а сейчас я блогер, активно веду свой Instagram-аккаунт о путешествиях, в которых меня всегда сопровождает собака породы хаски Спейс. Она мой лучший друг.',
        age: 26,
        pets: 'милейшая собака',
        city: 'Нью-Йорк',
      },
      {
        name: 'Илия',
        email: 'ilia@mail.ru',
        password: '123',
        phone: '8(926)924-82-42',
        social: 'https://instagram.com/elivosk?igshid=MDE2OWE1N2Q=',
        photo: 'images/ilia.jpeg',
        about: 'Привет! Меня зовут Илия я обычный человек, муж, папа, фотограф. Люблю путешествовать по скандинавским странам, а так же по России',
        drivLic: 'Водительские права категории В',
        telegram: 'elivosk',
      },
      {
        name: 'Александр',
        email: 'sasha@mail.ru',
        password: '123',
        phone: '8(921)987-24-51',
        social: 'https://instagram.com/alex.mazurov?igshid=MDE2OWE1N2Q=',
        photo: 'images/sasha.jpeg',
        about: 'Меня зовут Саша. Живу в Санкт-Петербурге, но очень часто путешествию по миру и по просторам родной страны',
        drivLic: 'Водительские права категории В',
        city: 'Санкт-Петербург',
        transport: 'SKODA OCTAVIA',
        telegram: 'withalexmazurov',
      },
      {
        name: 'Саша',
        email: 'sashagreb@mail.ru',
        password: '123',
        phone: '8(928)342-74-37',
        social: ' https://github.com/AlexGCoder',
        photo: 'images/alexgreb.png',
        city: 'Сочи',
        about: 'Меня зовут Саша. Живу в солнечном Сочи, где темные ночи. Очень люблю воду(озеро, море, океан) - главное, чтоб была гуд компания)))',
        drivLic: 'Водительские права категории В',
        pets: 'бойцовая собачка',
        telegram: 'AlexandrGrebennikov',
      },
      {
        name: 'Филипп',
        email: 'fill007@gmail.com',
        password: '123',
        phone: '8(929)560-74-10',
        social: 'https://github.com/Fil101',
        photo: 'images/fill.png',
        about: 'Меня зовут Филипп. Хочу проехать на своей тачке весь мир. Кто со мной?)',
        city: 'Москва',
        drivLic: 'Водительские права категории В, D',
        transport: 'Porsche',
        telegram: 'ost_jupiter',
      },
      {
        name: 'Эльдар',
        email: 'eldarus@ya.ru',
        password: '123',
        phone: '8(929)557-24-18',
        social: 'https://github.com/Abdullaev-Eldar',
        photo: 'images/eldar.png',
        city: 'Химки',
        drivLic: 'Водительские права категории A, В',
        pets: 'ручная крыска',
        transport: 'BMW X5',
        about: 'Люблю ночные поездки на мото. Веселые компании и нетронутые уголки дикой природы.',
        telegram: 'i_am_eldar',
      },
      {
        name: 'Ярослава',
        email: 'yara999@ya.ru',
        password: '123',
        phone: '8(916)497-76-14',
        social: 'https://github.com/makedonskyy',
        photo: 'images/yara.png',
        city: 'Чехов',
        about: 'Путешествия - это моя жизнь. Всегда в движении.',
        telegram: 'ymakedonsky',
      },
      {
        name: 'Марат',
        email: 'mar89@ya.ru',
        password: '123',
        phone: '8(920)564-76-57',
        social: 'https://vk.com/maratmix',
        photo: 'images/marat.png',
        city: 'Москва',
        telegram: 'Maratmix17',
        about: 'Блогер, путешественник, личный фотограф для жены)))',
      },
      {
        name: 'Маша',
        email: 'masha90@ya.ru',
        password: '123',
        phone: '8(929)730-77-23',
        social: 'https://vk.com/merrym',
        photo: 'images/masha.png',
        city: 'Москва',
        about: 'Веселая, люблю хорошие веселые компания и конечно же путешествовать и зимой и летом',
        telegram: 'KartonStyle',
      },
      {
        name: 'Таня',
        email: 'tan88@mail.ru',
        password: '123',
        phone: '8(918)501-13-13',
        social: 'https://vk.com/gilmanova_tv',
        photo: 'images/tanya.png',
        pets: 'киса Милана',
        city: 'Москва',
        transport: 'Тойота',
        about: 'Люблю красивые фото-, видео- в лучших уголках мира. ',
        telegram: 'gilmanova_tv',
      },

    ];

    await queryInterface.bulkInsert('Users', usersArr, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
